addQuestions('intermediate', [
  { q: '¿Qué rapaz emblemática de sierras mediterráneas se conoce también como águila de Bonelli?', a: ['Águila perdicera', 'Águila culebrera', 'Águila calzada'], correct: 0 },
  { q: '¿Qué especie de anátida amenazada cría en lagunas salobres y endorreicas del sureste peninsular?', a: ['Malvasía cabeciblanca', 'Ánade friso', 'Pato colorado'], correct: 0 },
  { q: '¿Qué limícola de pico muy largo y curvado hacia arriba usa los arrozales del Mediterráneo en paso migratorio?', a: ['Avoceta común', 'Zarapito real', 'Chorlito dorado'], correct: 0 },
  { q: '¿Qué ardeida pequeña y discreta se detecta por su vuelo bajo entre carrizos al atardecer?', a: ['Avetorillo común', 'Garceta grande', 'Garcilla cangrejera'], correct: 0 },
  { q: '¿Qué especie de gaviota mediterránea de conservación prioritaria nidifica en colonias en islas y salinas?', a: ['Gaviota de Audouin', 'Gaviota patiamarilla', 'Gaviota reidora'], correct: 0 },
  { q: '¿Qué rallidae de color azul violáceo y pico rojo ocupa carrizales y eneales de marjal?', a: ['Calamón común', 'Focha común', 'Rascón europeo'], correct: 0 },
  { q: '¿Qué charrán de pico rojo y negro con penacho corto cría en dunas y playas mediterráneas?', a: ['Charrán patinegro', 'Charrancito común', 'Charrán común'], correct: 0 },
  { q: '¿Qué chotacabras se asocia a pinares claros y matorral mediterráneo de baja altitud?', a: ['Chotacabras pardo', 'Chotacabras europeo', 'Chotacabras cuellirrojo'], correct: 0 },
  { q: '¿Cuál de estas currucas es típica del matorral termomediterráneo de jaras y brezos costeros?', a: ['Curruca rabilarga (Dartford)', 'Curruca carrasqueña', 'Curruca mosquitera'], correct: 0 },
  { q: '¿Qué ave esteparia de ojos grandes y patas largas ocupa mosaicos de barbechos y pedregales?', a: ['Alcaraván común', 'Sisón común', 'Ganga ortega'], correct: 0 },
  { q: '¿Qué paseriforme de colores turquesa y castaño cría en taludes y tendidos de llanuras cálidas?', a: ['Carraca europea', 'Abejaruco europeo', 'Tarabilla europea'], correct: 0 },
  { q: '¿Qué especie de garceta muestra penachos nupciales espectaculares en primavera?', a: ['Garceta común', 'Garceta grande', 'Garcilla bueyera'], correct: 0 },
  { q: '¿Qué mosquitero con canto rápido y chisporroteante se reproduce en encinares y alcornocales mediterráneos?', a: ['Mosquitero ibérico', 'Mosquitero musical', 'Mosquitero común'], correct: 0 },
  { q: '¿Qué limícola de alas largas realiza vuelos mariposeantes y nidifica en saladares?', a: ['Canastera común', 'Chorlitejo chico', 'Correlimos común'], correct: 0 },
  { q: '¿Qué especie marina estrictamente balear es endémica y muy amenazada?', a: ['Pardela balear', 'Pardela cenicienta', 'Paiño europeo'], correct: 0 },
  { q: '¿Qué ibis reintroducido en Cádiz y Marruecos aparece ocasionalmente en humedales mediterráneos?', a: ['Ibis eremita', 'Morito común', 'Ibis sagrado'], correct: 0 },
  { q: '¿Qué pequeña lechuza diurna y crepuscular ocupa olivares, dehesas y pueblos?', a: ['Mochuelo europeo', 'Lechuza común', 'Autillo europeo'], correct: 0 },
  { q: '¿Qué vencejo de mayor tamaño y dorso pardo se concentra en cortados costeros y sierras?', a: ['Vencejo cafre (vencejo moro)', 'Vencejo real', 'Vencejo común'], correct: 1 },
  { q: '¿Qué paseriforme muy ligado al matorral espinoso del sureste luce cola rojiza y ceja marcada?', a: ['Alzacola rojizo', 'Colirrojo real', 'Curruca tomillera'], correct: 0 },
  { q: '¿Qué rapaz planeadora migratoria cruza el Estrecho y se alimenta de reptiles en áreas mediterráneas?', a: ['Culebrera europea', 'Aguilucho lagunero', 'Milano negro'], correct: 0 },
  { q: '¿Qué zampullín de ojos rojos es habitual en charcas costeras y salinas?', a: ['Zampullín cuellinegro', 'Zampullín común', 'Zampullín macaceado'], correct: 0 },
  { q: '¿Qué especie de fringílido de máscara roja explota cardos y eriales mediterráneos?', a: ['Jilguero europeo', 'Verderón común', 'Pardillo común'], correct: 0 },
  { q: '¿Qué “pato buceador” de dorso gris y cabeza castaña forma grandes bandos en invernada mediterránea?', a: ['Porrón común', 'Ánade rabudo', 'Silbón europeo'], correct: 0 },
  { q: '¿Qué ave de plumaje achocolatado y cola muy larga se asocia a palmerales y huertas cálidas?', a: ['Rabilargo ibérico (Medit.)', 'Urraca común', 'Chova piquirroja'], correct: 0 },
  { q: '¿Qué ardeida ocre y blanca cría en colonias mixtas y suele posarse en carrizos?', a: ['Garcilla cangrejera', 'Garcilla bueyera', 'Garceta común'], correct: 0 },
  { q: '¿Qué paseriforme negro con destellos metálicos forma dormideros masivos en ciudades costeras?', a: ['Estornino negro', 'Mirlo común', 'Grajilla occidental'], correct: 0 },
  { q: '¿Qué lárido de dorso oscuro abunda en invierno en puertos y playas mediterráneos?', a: ['Gaviota sombría', 'Gaviota cana', 'Gaviota tridáctila'], correct: 0 },
  { q: '¿Qué ave esteparia de vuelo potente muestra pecho listado y alas con banda blanca?', a: ['Ganga ibérica', 'Ortega', 'Sisón común'], correct: 0 },
  { q: '¿Qué pícido verde con bigotera roja busca hormigas en claros de encinar?', a: ['Pito real ibérico', 'Pico picapinos', 'Picogordo'], correct: 0 },
  { q: '¿Qué passeriforme de dorso azul y pecho anaranjado excava galerías en taludes arenosos?', a: ['Abejaruco europeo', 'Avión zapador', 'Collalba rubia'], correct: 0 },
  { q: '¿Qué cormorán costero pequeño luce un penacho nupcial en primavera?', a: ['Cormorán moñudo', 'Cormorán grande', 'Alca torda'], correct: 0 },
  { q: '¿Qué zancuda de patas rojizas y pico largo negro cría en arrozales del Mediterráneo?', a: ['Cigüeñuela común', 'Archibebe común', 'Aguja colinegra'], correct: 0 },
  { q: '¿Qué escribano ligado a cultivos de secano muestra cabeza amarilla en el macho?', a: ['Escribano soteño', 'Escribano triguero', 'Escribano hortelano'], correct: 0 },
  { q: '¿Qué curruca de ceja blanca y garganta clara ocupa tomillares y coscojares?', a: ['Curruca carrasqueña', 'Curruca cabecinegra', 'Curruca zarcera'], correct: 0 },
  { q: '¿Qué focha con “escudo” frontal blanco es común en marjales y embalses costeros?', a: ['Focha común', 'Gallineta común', 'Calamón común'], correct: 0 },
  { q: '¿Qué rapaz pequeña y gregaria ocupa cortados urbanos y rurales en la Meseta Sur y Levante?', a: ['Cernícalo primilla', 'Cernícalo vulgar', 'Gavilán común'], correct: 0 },
  { q: '¿Qué colimbo/colimbo no es típico del Mediterráneo español en cría pero aparece en invernada en el litoral?', a: ['Somormujo lavanco', 'Colimbo grande', 'Zampullín cuellinegro'], correct: 1 },
  { q: '¿Qué ave marina de pico rojo y capirote negro pesca en llanos litorales y estuarios?', a: ['Charrán común', 'Gaviota cabecinegra', 'Alcatraz atlántico'], correct: 0 },
  { q: '¿Qué ánade pequeño de espejo verde y pico gris abunda en humedales costeros en invierno?', a: ['Cerceta común', 'Ánade silbón', 'Ánade azulón'], correct: 0 },
  { q: '¿Qué ruiseñor de cola rojiza inverna escasamente en litorales templados y ocupa jardines?', a: ['Colirrojo tizón', 'Ruiseñor común', 'Papamoscas cerrojillo'], correct: 0 },
  { q: '¿Qué ave de gran envergadura planea sobre sierras litorales aprovechando térmicas?', a: ['Buitre leonado', 'Milano real', 'Águila imperial ibérica'], correct: 0 }
]);
