addQuestions('easy', [
  { q: '¿Qué ave rapaz es muy común en la España mediterránea y se reconoce por su silueta en forma de cometa?', a: ['Milano real', 'Buitre negro', 'Águila imperial'], correct: 0 },
  { q: '¿Qué ave marina anida en las islas Baleares y está en peligro de extinción?', a: ['Pardela balear', 'Gaviota reidora', 'Cormorán grande'], correct: 0 },
  { q: '¿Qué ave de gran tamaño se encuentra en humedales mediterráneos como la Albufera de Valencia?', a: ['Garza real', 'Halcón peregrino', 'Abubilla'], correct: 0 },
  { q: '¿Qué ave de plumaje rosado se agrupa en grandes bandadas en salinas y marjales?', a: ['Flamenco', 'Cigüeña blanca', 'Cernícalo'], correct: 0 },
  { q: '¿Cuál es el ave rapaz más pequeña de la Península Ibérica?', a: ['Cernícalo vulgar', 'Águila calzada', 'Azor'], correct: 0 },
  { q: '¿Qué ave forestal destaca por su canto repetitivo “cu-cu”?', a: ['Cuco', 'Alcaudón', 'Verderón'], correct: 0 },
  { q: '¿Qué ave de colores llamativos tiene pico largo y cazador de insectos voladores?', a: ['Abejaruco europeo', 'Tórtola turca', 'Gorrión común'], correct: 0 },
  { q: '¿Qué ave nocturna de gran tamaño se encuentra en sierras mediterráneas?', a: ['Búho real', 'Lechuza común', 'Autillo europeo'], correct: 0 },
  { q: '¿Qué ave pequeña y cantora se asocia con los olivares y huertos mediterráneos?', a: ['Ruiseñor común', 'Graja', 'Arrendajo'], correct: 0 },
  { q: '¿Qué ave planeadora de gran envergadura se observa a menudo en acantilados mediterráneos?', a: ['Buitre leonado', 'Aguilucho lagunero', 'Milano negro'], correct: 0 },
  { q: '¿Qué especie de paloma es muy común en ciudades y pueblos mediterráneos?', a: ['Paloma bravía', 'Tórtola común', 'Paloma torcaz'], correct: 0 },
  { q: '¿Qué ave zancuda blanca y negra es conocida por anidar en campanarios?', a: ['Cigüeña blanca', 'Garza imperial', 'Ibis eremita'], correct: 0 },
  { q: '¿Qué ave de plumaje azul eléctrico es típica de ríos mediterráneos?', a: ['Martín pescador', 'Azulejo', 'Colirrojo tizón'], correct: 0 },
  { q: '¿Qué ave pequeña se reconoce por su copete y vive en campos de cultivo?', a: ['Cogujada común', 'Mirlo común', 'Lavandera blanca'], correct: 0 },
  { q: '¿Qué ave playera corretea por las playas levantinas con movimientos rápidos?', a: ['Chorlitejo patinegro', 'Correlimos común', 'Avefría'], correct: 0 },
  { q: '¿Qué ave rapaz se asocia con cortados y montañas y es símbolo de libertad?', a: ['Águila real', 'Gavilán', 'Cernícalo primilla'], correct: 0 },
  { q: '¿Qué ave cantora es famosa por imitar los sonidos de su entorno?', a: ['Estornino negro', 'Jilguero', 'Verderón'], correct: 0 },
  { q: '¿Qué ave insectívora de plumaje blanco y negro mueve constantemente la cola?', a: ['Lavandera blanca', 'Golondrina común', 'Collalba gris'], correct: 0 },
  { q: '¿Qué ave migratoria llega en primavera y construye nidos de barro bajo los tejados?', a: ['Golondrina común', 'Vencejo común', 'Avión zapador'], correct: 0 },
  { q: '¿Qué ave rapaz nocturna se reconoce por su “uh-hu” profundo?', a: ['Búho real', 'Mochuelo europeo', 'Autillo'], correct: 0 },
  { q: '¿Qué ave paseriforme destaca por su canto alegre en primavera?', a: ['Jilguero', 'Carbonero común', 'Tórtola europea'], correct: 0 },
  { q: '¿Qué ave grande y blanca suele verse volando en estuarios y marismas?', a: ['Garza blanca', 'Gaviota patiamarilla', 'Charrán común'], correct: 0 },
  { q: '¿Qué ave rapaz se cierne en el aire antes de lanzarse sobre su presa?', a: ['Cernícalo vulgar', 'Águila pescadora', 'Azor común'], correct: 0 },
  { q: '¿Qué ave de plumaje marrón y cresta llamativa es famosa por su canto “upu-upu”?', a: ['Abubilla', 'Alcaudón real', 'Grajilla'], correct: 0 },
  { q: '¿Qué ave marina suele seguir a los barcos pesqueros en el Mediterráneo?', a: ['Gaviota patiamarilla', 'Cormorán moñudo', 'Charrán ártico'], correct: 0 },
  { q: '¿Qué ave rapaz delgada y veloz es famosa por ser la más rápida del mundo?', a: ['Halcón peregrino', 'Águila perdicera', 'Esmerejón'], correct: 0 },
  { q: '¿Qué ave pequeña canta al amanecer y es símbolo de alegría en el campo?', a: ['Alondra común', 'Carbonero garrapinos', 'Verderón común'], correct: 0 },
  { q: '¿Qué ave rapaz pescadora se observa en lagunas y embalses mediterráneos?', a: ['Águila pescadora', 'Milano negro', 'Busardo ratonero'], correct: 0 },
  { q: '¿Qué ave anida en colonias en acantilados marinos de la costa mediterránea?', a: ['Gaviota de Audouin', 'Alcatraz atlántico', 'Pardela cenicienta'], correct: 0 },
  { q: '¿Qué ave forestal es especialista en trepar troncos y picar madera?', a: ['Pico picapinos', 'Arrendajo', 'Zorzal común'], correct: 0 },
  { q: '¿Qué ave insectívora vuela de forma acrobática en verano sobre los pueblos mediterráneos?', a: ['Vencejo común', 'Avión roquero', 'Golondrina dáurica'], correct: 0 },
  { q: '¿Qué ave acuática bucea para pescar peces en costas mediterráneas?', a: ['Cormorán grande', 'Charrán común', 'Somormujo lavanco'], correct: 0 },
  { q: '¿Qué ave es conocida como “pájaro carpintero verde” en bosques mediterráneos?', a: ['Pito real', 'Trepador azul', 'Carbonero común'], correct: 0 },
  { q: '¿Qué ave rapaz se asocia a encinares y pinares y caza aves en vuelo?', a: ['Azor común', 'Aguilucho cenizo', 'Buitre negro'], correct: 0 },
  { q: '¿Qué ave limícola de pico largo se alimenta en charcas y arrozales?', a: ['Cigüeñuela común', 'Correlimos tridáctilo', 'Chorlito gris'], correct: 0 },
  { q: '¿Qué ave típica de matorrales mediterráneos es pequeña y de canto fuerte?', a: ['Curruca cabecinegra', 'Petirrojo', 'Verderón'], correct: 0 },
  { q: '¿Qué ave grande y blanca es símbolo de la llegada de la primavera en pueblos mediterráneos?', a: ['Cigüeña blanca', 'Garza real', 'Flamenco'], correct: 0 },
  { q: '¿Qué ave rapaz mediana es conocida por sus alas en forma de “M” al volar?', a: ['Aguilucho lagunero', 'Águila calzada', 'Gavilán común'], correct: 0 },
  { q: '¿Qué ave marina negra con penacho es típica de las costas rocosas mediterráneas?', a: ['Cormorán moñudo', 'Gaviota sombría', 'Alca común'], correct: 0 },
  { q: '¿Qué ave insectívora pequeña canta en jardines y parques mediterráneos?', a: ['Petirrojo europeo', 'Carbonero común', 'Estornino negro'], correct: 0 }
]);
