addQuestions('intermediate', [
  { q: '¿Cuál es el verdadero propósito del programa genético Bene Gesserit?', a: ['Crear al Kwisatz Haderach', 'Fundar una nueva Casa', 'Dominar la CHOAM'], correct: 0 },
  { q: '¿Qué prueba de iniciación enfrenta Paul con la caja y el gom jabbar?', a: ['Resistir el dolor sin retirar la mano', 'Luchar contra un Sardaukar', 'Atrapar un gusano de arena'], correct: 0 },
  { q: '¿Por qué los escudos personales no se usan en Arrakis?', a: ['Atraen a los gusanos de arena', 'Se derriten con la especia', 'Absorben demasiada energía solar'], correct: 0 },
  { q: '¿Qué recurso sustituye al dinero en la sociedad Fremen?', a: ['El agua', 'La especia', 'Los gusanos'], correct: 0 },
  { q: '¿Qué ritual Fremen recicla el agua de los muertos?', a: ['El “reclaim”', 'La disciplina del agua', 'La ceremonia Sayyadina'], correct: 0 },
  { q: '¿Qué nombre recibe Paul tras superar las pruebas Fremen?', a: ['Muad’Dib', 'Shai-Hulud', 'Mahdi'], correct: 0 },
  { q: '¿Cuál es el parentesco entre Feyd-Rautha y el Barón Harkonnen?', a: ['Sobrino', 'Hijo', 'Hermano'], correct: 0 },
  { q: '¿Qué revela la profecía Bene Gesserit implantada en Arrakis?', a: ['La llegada del Lisan al-Gaib', 'La creación de un nuevo sietch', 'El retorno del Emperador'], correct: 0 },
  { q: '¿Qué planeta es descrito como prisión y forja de los Sardaukar?', a: ['Salusa Secundus', 'Ix', 'Caladan'], correct: 0 },
  { q: '¿Qué visión atormenta a Paul sobre su posible futuro?', a: ['Una jihad galáctica en su nombre', 'El colapso del Imperio', 'Su muerte en Caladan'], correct: 0 },
  { q: '¿Qué ocurre si un gusano de arena joven es ahogado en agua?', a: ['Se transforma en Agua de Vida', 'Muere y produce especia sólida', 'Se convierte en gusano mayor'], correct: 0 },
  { q: '¿Quién es Liet-Kynes en realidad además de planetólogo imperial?', a: ['Líder secreto de los Fremen', 'Príncipe de Ix', 'Agente de los Tleilaxu'], correct: 0 },
  { q: '¿Cómo sobreviven los navegantes del Gremio en la navegación espacial?', a: ['Usando especia para doblar el espacio', 'Con implantes mecánicos', 'Con ayuda de Sardaukar'], correct: 0 },
  { q: '¿Qué efecto produce la especia en los mentats y Bene Gesserit?', a: ['Aumenta sus capacidades mentales', 'Los ciega', 'Provoca pérdida de memoria'], correct: 0 },
  { q: '¿Qué significa “Kanly” en el universo de Dune?', a: ['Vendetta entre Casas', 'Juramento Fremen', 'Contrato comercial'], correct: 0 },
  { q: '¿Qué es la CHOAM?', a: ['La corporación que controla el comercio del Imperio', 'Un sietch principal', 'La orden secreta de los Tleilaxu'], correct: 0 },
  { q: '¿Qué arma secreta entrega Yueh al Duque Leto?', a: ['Un diente hueco con veneno', 'Un crysknife envenenado', 'Un ornitóptero modificado'], correct: 0 },
  { q: '¿Qué habilidad especial desarrolla Alia, la hermana de Paul?', a: ['Acceso a las memorias ancestrales', 'Ver el futuro a voluntad', 'Dominar a los gusanos de arena'], correct: 0 },
  { q: '¿Cómo llaman los Fremen al Mesías esperado?', a: ['Mahdi', 'Naib', 'Sayyadina'], correct: 0 },
  { q: '¿Qué diferencia existe entre un Naib y un Sayyadina en los Fremen?', a: ['El Naib es jefe del sietch y la Sayyadina es sacerdotisa', 'El Naib es guerrero y la Sayyadina curandera', 'El Naib es maestro y la Sayyadina alumna'], correct: 0 },
  { q: '¿Qué significa “Lisan al-Gaib” para los Fremen?', a: ['La Voz del Exterior', 'El Señor de los Gusanos', 'El Profeta de la Especia'], correct: 0 },
  { q: '¿Quién instruye a Paul en combate con armas y poesía?', a: ['Gurney Halleck', 'Duncan Idaho', 'Thufir Hawat'], correct: 0 },
  { q: '¿Qué recurso necesitan los Fremen para montar a los gusanos de arena?', a: ['Anzuelos especiales', 'Especia líquida', 'Escudos'], correct: 0 },
  { q: '¿Qué función cumple la especia en la economía imperial?', a: ['Es la base de todo comercio', 'Sirve como moneda Fremen', 'Se usa solo en medicina'], correct: 0 },
  { q: '¿Qué miedo confiesa la Bene Gesserit sobre el Kwisatz Haderach?', a: ['Que escape a su control', 'Que muera joven', 'Que no nazca'], correct: 0 },
  { q: '¿Qué representa el término “Agua de Vida” para los Fremen?', a: ['Veneno transmutado por una Reverenda Madre', 'Agua del sietch sagrada', 'La esencia de los Naibs'], correct: 0 },
  { q: '¿Cómo resisten las Bene Gesserit el control de la Voz de otra?', a: ['Con entrenamiento en Voz', 'Con tapones auditivos', 'Con meditación'], correct: 0 },
  { q: '¿Qué es un crysknife en la tradición Fremen?', a: ['Un cuchillo hecho de colmillo de gusano', 'Un sable metálico', 'Un puñal imperial'], correct: 0 },
  { q: '¿Qué provoca el “spice agony”?', a: ['La ingestión de Agua de Vida por una Bene Gesserit', 'La pérdida de especia', 'El exceso de destiltraje'], correct: 0 },
  { q: '¿Qué objetivo tenía el Barón Harkonnen en Arrakis?', a: ['Explotar la especia y destruir a los Atreides', 'Crear una base militar secreta', 'Conquistar a los Fremen'], correct: 0 },
  { q: '¿Qué ocurre con los ojos de los Fremen por consumo de especia?', a: ['Se vuelven azul dentro de azul', 'Se vuelven rojos', 'Se tornan verdes'], correct: 0 },
  { q: '¿Qué es el “weirding way” de las Bene Gesserit?', a: ['Un estilo de combate veloz y preciso', 'Un canto religioso', 'Un ritual funerario'], correct: 0 },
  { q: '¿Qué significa “Sietch Tabr” en la vida de Paul?', a: ['Su hogar entre los Fremen', 'La capital imperial', 'El palacio del Barón'], correct: 0 },
  { q: '¿Qué instrumento toca Gurney Halleck además de luchar?', a: ['La baliseta', 'El laúd', 'La zanfona'], correct: 0 },
  { q: '¿Qué temen los Fremen sobre revelar sus reservas de agua?', a: ['Que el Imperio las robe', 'Que los gusanos mueran', 'Que desaparezca la especia'], correct: 0 },
  { q: '¿Qué título recibe Paul al final de la primera novela?', a: ['Emperador del Imperio', 'Naib de Sietch Tabr', 'Kwisatz Haderach de los Bene Tleilax'], correct: 0 },
  { q: '¿Qué significa la expresión Fremen “El desierto es nuestro mar”?', a: ['Que el desierto es su mundo y medio de vida', 'Que buscan colonizar océanos', 'Que veneran a los gusanos como peces'], correct: 0 },
  { q: '¿Qué función cumple el mentat en una Casa noble?', a: ['Asesor lógico y estratégico', 'Comandante militar', 'Orador del Landsraad'], correct: 0 },
  { q: '¿Qué resultado produce la jihad que Paul teme?', a: ['Una guerra religiosa devastadora en su nombre', 'La paz universal inmediata', 'La muerte de los Fremen'], correct: 0 },
  { q: '¿Qué habilidad extra tienen los navegantes del Gremio gracias a la especia?', a: ['Presciencia limitada', 'Inmortalidad completa', 'Control mental total'], correct: 0 }
]);
