addQuestions('easy', [
  { q: '¿Cómo se llama el planeta desértico donde transcurre la mayor parte de Dune?', a: ['Arrakis', 'Caladan', 'Kaitain'], correct: 0 },
  { q: '¿Cómo se llama la sustancia más valiosa del universo en Dune?', a: ['Melange (especia)', 'Aqua Vitae', 'Plutonio'], correct: 0 },
  { q: '¿Quién es el protagonista principal de Dune?', a: ['Paul Atreides', 'Feyd-Rautha', 'Miles Teg'], correct: 0 },
  { q: '¿Cómo se llama la madre de Paul Atreides?', a: ['Lady Jessica', 'Chani', 'Irulan'], correct: 0 },
  { q: '¿Cómo se llama el padre de Paul Atreides?', a: ['Duque Leto Atreides', 'Thufir Hawat', 'Duncan Idaho'], correct: 0 },
  { q: '¿Cómo se llama el pueblo nativo del desierto de Arrakis?', a: ['Fremen', 'Sardaukar', 'Ixianos'], correct: 0 },
  { q: '¿Cómo llaman los Fremen a los gusanos gigantes?', a: ['Shai-Hulud', 'Leviatán', 'Sandrider'], correct: 0 },
  { q: '¿Cuál es el planeta natal de la Casa Atreides antes de ir a Arrakis?', a: ['Caladan', 'Giedi Prime', 'Salusa Secundus'], correct: 0 },
  { q: '¿Cuál es el planeta natal de la Casa Harkonnen?', a: ['Giedi Prime', 'Caladan', 'Ix'], correct: 0 },
  { q: '¿Cómo se llama el Emperador durante los sucesos de Dune?', a: ['Shaddam IV', 'Elrood IX', 'Leto II'], correct: 0 },
  { q: '¿Cómo se llaman los soldados de élite del Emperador?', a: ['Sardaukar', 'Fedaykin', 'Lancers'], correct: 0 },
  { q: '¿Cómo se llama la orden femenina a la que pertenece Jessica?', a: ['Bene Gesserit', 'Tleilaxu', 'Honored Matres'], correct: 0 },
  { q: '¿Qué es un Mentat en el universo de Dune?', a: ['Un humano entrenado para cálculos y estrategia', 'Un robot', 'Un sacerdote del desierto'], correct: 0 },
  { q: '¿Qué organización controla la navegación estelar?', a: ['Gremio Espacial', 'CHOAM', 'Bene Tleilax'], correct: 0 },
  { q: '¿Cómo llaman los Fremen a sus cuchillos sagrados hechos de diente de gusano?', a: ['Crysknife', 'Kindjal', 'Krysblade'], correct: 0 },
  { q: '¿Qué vehículo volador característico se usa en Arrakis?', a: ['Ornitóptero', 'Speeder', 'Valkiria'], correct: 0 },
  { q: '¿Qué color de ojos presentan quienes consumen especia de forma habitual?', a: ['Azul dentro de azul', 'Verde esmeralda', 'Dorado ámbar'], correct: 0 },
  { q: '¿Cómo llaman los Fremen al agua por su valor vital?', a: ['La vida', 'La sal', 'El velo'], correct: 0 },
  { q: '¿Cuál es el nombre Fremen que adopta Paul?', a: ['Muad’Dib', 'Usul', 'Farok'], correct: 0 },
  { q: '¿Cómo se llama la compañera Fremen de Paul?', a: ['Chani', 'Irulan', 'Harah'], correct: 0 },
  { q: '¿Quién lidera a los Fremen cuando Paul los conoce?', a: ['Stilgar', 'Jamis', 'Otheym'], correct: 0 },
  { q: '¿Quién es el médico que traiciona a los Atreides?', a: ['Dr. Yueh', 'Dr. Kynes', 'Dr. Wellington'], correct: 0 },
  { q: '¿Quién es el Mentat y Maestro de Asesinos de los Atreides?', a: ['Thufir Hawat', 'Piter de Vries', 'Wanna Yueh'], correct: 0 },
  { q: '¿Qué guerrero-músico sirve a la Casa Atreides y toca la baliseta?', a: ['Gurney Halleck', 'Duncan Idaho', 'Glossu Rabban'], correct: 0 },
  { q: '¿Quién es el Mentat de los Harkonnen?', a: ['Piter de Vries', 'Thufir Hawat', 'Hasimir Fenring'], correct: 0 },
  { q: '¿Cómo se llama la Reverenda Madre que examina a Paul con el gom jabbar?', a: ['Gaius Helen Mohiam', 'Ramallo', 'Harishka'], correct: 0 },
  { q: '¿Quién es el planetólogo imperial destinado en Arrakis?', a: ['Liet-Kynes', 'Hasimir Fenring', 'Count Kynes'], correct: 0 },
  { q: '¿Cómo se llaman las fuerzas de élite Fremen leales a Paul?', a: ['Fedaykin', 'Sietch Guard', 'Naibs'], correct: 0 },
  { q: '¿Cómo se llaman los asentamientos Fremen en el desierto?', a: ['Sietch', 'Qasar', 'Arrakeen'], correct: 0 },
  { q: '¿Cómo se llama el traje que recicla la humedad corporal en el desierto?', a: ['Destiltraje (stillsuit)', 'Traje termoiónico', 'Traje refractario'], correct: 0 },
  { q: '¿Cómo se denomina la ley del honor y vendetta entre Casas?', a: ['Kanly', 'Jus Honoris', 'Lex Atreides'], correct: 0 },
  { q: '¿Cómo se llama la aguja venenosa usada en la prueba del dolor a Paul?', a: ['Gom jabbar', 'Kusari', 'Kanly pin'], correct: 0 },
  { q: '¿Qué significa el término “Kwisatz Haderach”?', a: ['El acortamiento del camino profético', 'El señor del agua', 'El domador de gusanos'], correct: 0 },
  { q: '¿Cuál es la capital o ciudad principal de Arrakis durante los Atreides?', a: ['Arrakeen', 'Carthag', 'Tsimpo'], correct: 0 },
  { q: '¿Cómo se llama la hija del Emperador Shaddam IV?', a: ['Princesa Irulan', 'Princesa Wensicia', 'Princesa Alia'], correct: 0 },
  { q: '¿Qué corporación regula el comercio interplanetario junto al Gremio?', a: ['CHOAM', 'IX-Trade', 'Spacing Ltd.'], correct: 0 },
  { q: '¿Qué efecto básico tiene la especia en los humanos?', a: ['Prolonga la vida y amplía la conciencia', 'Provoca ceguera inmediata', 'Elimina la necesidad de agua'], correct: 0 },
  { q: '¿Cómo se llama el Barón que lidera a los Harkonnen?', a: ['Vladimir Harkonnen', 'Feyd-Rautha Harkonnen', 'Rabban Harkonnen'], correct: 0 },
  { q: '¿Qué mundo es famoso como planeta-prisión y campo de entrenamiento de Sardaukar?', a: ['Salusa Secundus', 'Kaitain', 'Richese'], correct: 0 },
  { q: '¿Qué nombre reciben los helicópteros con alas batientes en Dune?', a: ['Ornitópteros', 'Skimmers', 'Falcons'], correct: 0 },
  { q: '¿Cómo llaman los Fremen a Paul en el círculo íntimo, además de Muad’Dib?', a: ['Usul', 'Mahdi', 'Sihaya'], correct: 0 }
]);
