addQuestions('hard', [
  { q: '¿Qué título adopta Paul Atreides al convertirse en líder religioso y político en Arrakis?', a: ['Muad’Dib', 'Padishah', 'Naib'], correct: 0 },
  { q: '¿Qué significa realmente “Kwisatz Haderach” en la tradición Bene Gesserit?', a: ['El acortamiento del camino, capaz de acceder a ambos futuros', 'El guerrero supremo', 'El padre de todas las Casas'], correct: 0 },
  { q: '¿Qué visión aterra más a Paul durante su despertar profético?', a: ['Una jihad galáctica en su nombre', 'La destrucción de Caladan', 'El triunfo absoluto de los Harkonnen'], correct: 0 },
  { q: '¿Qué efecto irreversible produce la “Agua de Vida” en las Bene Gesserit que sobreviven al trance?', a: ['Convertirse en Reverendas Madres con memorias ancestrales', 'Perder la vista', 'Unir su mente al Kwisatz Haderach'], correct: 0 },
  { q: '¿Quién es Hasimir Fenring dentro de la corte imperial?', a: ['Asesor y asesino secreto del Emperador', 'El líder de la CHOAM', 'El embajador de Ix'], correct: 0 },
  { q: '¿Qué función cumple la “Misiónaria Protectiva” de las Bene Gesserit?', a: ['Implantar mitos en planetas lejanos', 'Entrenar a nuevas Acolytes', 'Crear venenos específicos'], correct: 0 },
  { q: '¿Qué papel desempeña el Barón Harkonnen en la crianza de Feyd-Rautha?', a: ['Prepararlo como heredero y peón político', 'Convertirlo en un mentat', 'Ofrecerlo a las Bene Gesserit'], correct: 0 },
  { q: '¿Qué relación secreta une a Lady Jessica con los Harkonnen?', a: ['Es hija ilegítima del Barón', 'Fue entrenada por Feyd-Rautha', 'Es hermana de Rabban'], correct: 0 },
  { q: '¿Qué táctica clave permite a Paul derrotar a los Sardaukar en Arrakis?', a: ['Uso de la guerra de guerrillas Fremen y gusanos', 'Uso de escudos personales', 'Uso de armas atómicas'], correct: 0 },
  { q: '¿Qué recurso espiritual da cohesión a los Fremen además del agua y la especia?', a: ['Las profecías del Mahdi', 'Los cantos a Shai-Hulud', 'La lealtad a la CHOAM'], correct: 0 },
  { q: '¿Por qué el Emperador Shaddam IV teme a la Casa Atreides?', a: ['Por su creciente popularidad y ejército disciplinado', 'Por su riqueza minera en Ix', 'Por sus alianzas con Tleilaxu'], correct: 0 },
  { q: '¿Qué revela Paul al consumir especia en grandes cantidades durante el desierto?', a: ['Visiones del futuro inevitable', 'El secreto del Barón', 'La fórmula de la Agua de Vida'], correct: 0 },
  { q: '¿Qué simboliza el ratón del desierto (Muad’Dib) para Paul?', a: ['Su guía en el desierto y su nuevo nombre', 'El emblema imperial', 'La señal de los Sardaukar'], correct: 0 },
  { q: '¿Qué límite encuentran las Bene Gesserit en su acceso a memorias ancestrales?', a: ['No pueden ver el futuro masculino', 'Solo recuerdan tres generaciones', 'Se pierden en visiones falsas'], correct: 0 },
  { q: '¿Qué significa que los Fremen hablen de “agua vinculada” en un sietch?', a: ['El agua almacenada como riqueza común', 'El agua perdida en combate', 'El agua prohibida por el Emperador'], correct: 0 },
  { q: '¿Qué castigo reciben los traidores entre los Fremen?', a: ['Ser entregados al desierto sin destiltraje', 'Ser ejecutados por el Naib', 'Ser vendidos al Emperador'], correct: 0 },
  { q: '¿Qué revelación realiza el Dr. Yueh en su traición a los Atreides?', a: ['Que no puede resistir el condicionamiento Suk totalmente', 'Que siempre fue un agente Sardaukar', 'Que deseaba convertirse en Naib'], correct: 0 },
  { q: '¿Qué papel juega la CHOAM en la estabilidad del Imperio?', a: ['Distribuye las ganancias de la especia entre las Casas', 'Controla la formación militar', 'Elige al Emperador'], correct: 0 },
  { q: '¿Qué simbolismo tiene la transformación de Paul en Muad’Dib para los Fremen?', a: ['El cumplimiento de una profecía mesiánica', 'El inicio de la paz definitiva', 'La unión de todos los planetas del Landsraad'], correct: 0 },
  { q: '¿Qué significa que el Kwisatz Haderach pueda “estar en muchos lugares a la vez”?', a: ['Acceso simultáneo a futuros posibles', 'Dominar varias Casas a la vez', 'Multiplicarse físicamente'], correct: 0 },
  { q: '¿Qué rol cumple la Princesa Irulan en el ascenso de Paul?', a: ['Su matrimonio político para legitimar el trono', 'Su aliada secreta contra los Harkonnen', 'Su maestra en tácticas Fremen'], correct: 0 },
  { q: '¿Qué destino trágico sufre la Casa Harkonnen al final de Dune?', a: ['Derrota militar y muerte del Barón', 'Conversión en esclavos Fremen', 'Exilio a Ix'], correct: 0 },
  { q: '¿Qué representa Salusa Secundus en el equilibrio del Imperio?', a: ['La cantera de los Sardaukar', 'La capital del Landsraad', 'El centro de comercio CHOAM'], correct: 0 },
  { q: '¿Qué importancia tiene la “disciplina del agua” en la cultura Fremen?', a: ['Regula el uso colectivo y sagrado del agua', 'Impone impuestos imperiales', 'Controla los destiltrajes oficiales'], correct: 0 },
  { q: '¿Qué significa para los Fremen enterrar a un muerto en el desierto sin reclaim?', a: ['Una ofensa que desperdicia agua', 'Un honor reservado a los Naibs', 'Un tributo al Emperador'], correct: 0 },
  { q: '¿Qué enseñanza transmite la Bene Gesserit sobre el miedo en la liturgia de Paul?', a: ['El “Lema contra el miedo”: el miedo mata la mente', 'El miedo es necesario para sobrevivir', 'El miedo da fuerza en combate'], correct: 0 },
  { q: '¿Qué función tiene la “voz” Bene Gesserit?', a: ['Controlar a otros a través de entonación', 'Romper destiltrajes enemigos', 'Dominar a los gusanos'], correct: 0 },
  { q: '¿Qué diferencia esencial hay entre Muad’Dib y un mesías artificial de la Misiónaria Protectiva?', a: ['Muad’Dib es real, no fabricado', 'Muad’Dib usa escudos', 'Muad’Dib pertenece al Emperador'], correct: 0 },
  { q: '¿Qué papel juega Stilgar tras aceptar a Paul como líder?', a: ['Convertirse en su consejero y general Fremen', 'Abandonar el sietch', 'Unirse a los Harkonnen'], correct: 0 },
  { q: '¿Qué dilema enfrenta Paul al casarse con Irulan?', a: ['Dejar a Chani relegada aunque sea su verdadero amor', 'Aceptar convertirse en Emperador', 'Adoptar a los Harkonnen'], correct: 0 },
  { q: '¿Qué secreto sobre el Barón descubre Paul en el clímax?', a: ['Que es abuelo materno de Paul', 'Que es aliado de Ix', 'Que en realidad teme a los gusanos'], correct: 0 },
  { q: '¿Qué revela la especia sobre la mortalidad humana?', a: ['Puede prolongar la vida de forma extraordinaria', 'Otorga inmortalidad absoluta', 'Destruye la memoria'], correct: 0 },
  { q: '¿Qué significa el ascenso de Paul al trono imperial para el Landsraad?', a: ['Un cambio en el equilibrio de todas las Casas', 'La disolución del Landsraad', 'El inicio de la paz eterna'], correct: 0 },
  { q: '¿Qué destino le espera a Rabban tras la victoria Fremen?', a: ['Ser asesinado y reemplazado por Feyd', 'Gobernar Arrakis en paz', 'Exiliarse a Kaitain'], correct: 0 },
  { q: '¿Qué rol cumple la princesa Irulan después de la boda?', a: ['Cronista de la vida de Paul', 'Comandante de Sardaukar', 'Guerrera del sietch'], correct: 0 },
  { q: '¿Qué temor expresa Paul sobre su hijo aún no nacido con Chani?', a: ['Que sea usado como herramienta política', 'Que no herede sus poderes', 'Que sea adoptado por Irulan'], correct: 0 },
  { q: '¿Qué estrategia militar usan los Fremen contra los escudos imperiales?', a: ['Atacar con proyectiles lentos que penetran el campo', 'Atacar con rayos láser potentes', 'Ignorarlos en combate'], correct: 0 },
  { q: '¿Qué revela la muerte del Barón a manos de Alia?', a: ['Que incluso una niña puede portar memorias ancestrales y usar veneno', 'Que los Harkonnen eran inmortales', 'Que el Barón era inocente del todo'], correct: 0 },
  { q: '¿Qué simboliza la especia como elemento narrativo en Dune?', a: ['El poder absoluto y la dependencia universal', 'La riqueza de Caladan', 'Un mito sin importancia'], correct: 0 }
]);
