addQuestions('intermediate', [
  { q: '¿Qué general quedó al mando del bando sublevado tras la muerte de Sanjurjo?', a: ['Francisco Franco', 'Emilio Mola', 'Queipo de Llano'], correct: 0 },
  { q: '¿Qué dirigente republicano fue presidente del Gobierno durante buena parte de la guerra?', a: ['Juan Negrín', 'Francisco Largo Caballero', 'Manuel Azaña'], correct: 0 },
  { q: '¿Qué dirigente republicano fue conocido como “el Lenin español”?', a: ['Francisco Largo Caballero', 'Indalecio Prieto', 'Dolores Ibárruri'], correct: 0 },
  { q: '¿Quién pronunció la famosa frase “¡No pasarán!” durante la defensa de Madrid?', a: ['Dolores Ibárruri', 'La Pasionaria', 'Clara Campoamor'], correct: 0 },
  { q: '¿Qué general sublevado fue conocido como “el Director” del golpe de 1936?', a: ['Emilio Mola', 'Francisco Franco', 'Millán-Astray'], correct: 0 },
  { q: '¿Qué región española permaneció leal a la República desde el inicio hasta el final?', a: ['Cataluña', 'Galicia', 'Navarra'], correct: 0 },
  { q: '¿Qué dirigente anarquista fue asesinado en mayo de 1937 en Barcelona?', a: ['Andreu Nin', 'Buenaventura Durruti', 'Francisco Ascaso'], correct: 0 },
  { q: '¿Qué importante líder anarquista murió en noviembre de 1936 en Madrid?', a: ['Buenaventura Durruti', 'Federica Montseny', 'Diego Abad de Santillán'], correct: 0 },
  { q: '¿Qué nombre recibió la política económica de Negrín para sostener el esfuerzo bélico?', a: ['Resistir es vencer', 'Reforma agraria urgente', 'Autarquía inmediata'], correct: 0 },
  { q: '¿Qué ciudad se convirtió en símbolo de la resistencia republicana durante casi toda la guerra?', a: ['Madrid', 'Sevilla', 'Toledo'], correct: 0 },
  { q: '¿Qué famoso escritor estadounidense cubrió la guerra como periodista?', a: ['Ernest Hemingway', 'John Steinbeck', 'William Faulkner'], correct: 0 },
  { q: '¿Qué escritor británico participó en la guerra y escribió “Homenaje a Cataluña”?', a: ['George Orwell', 'Aldous Huxley', 'Evelyn Waugh'], correct: 0 },
  { q: '¿Qué misión cumplía la Legión Cóndor alemana en España?', a: ['Apoyo aéreo a los nacionales', 'Luchar como infantería en el frente', 'Formar guerrillas en el norte'], correct: 0 },
  { q: '¿Qué gran batalla en 1937 fue decisiva para frenar el avance nacional hacia Madrid?', a: ['Batalla de Guadalajara', 'Batalla de Teruel', 'Batalla del Jarama'], correct: 0 },
  { q: '¿Qué batallón de las Brigadas Internacionales estaba compuesto por voluntarios británicos?', a: ['Batallón Británico', 'Batallón Abraham Lincoln', 'Batallón Garibaldi'], correct: 0 },
  { q: '¿Qué batallón estaba formado principalmente por voluntarios estadounidenses?', a: ['Batallón Abraham Lincoln', 'Batallón Garibaldi', 'Batallón Dombrowski'], correct: 0 },
  { q: '¿Qué batalla de 1938 fue la más larga y sangrienta de la guerra?', a: ['Batalla del Ebro', 'Batalla de Brunete', 'Batalla de Belchite'], correct: 0 },
  { q: '¿Qué consecuencia tuvo la derrota republicana en la Batalla del Ebro?', a: ['Aislamiento de Cataluña', 'Pérdida de Sevilla', 'Caída de Madrid'], correct: 0 },
  { q: '¿Qué país envió la “Legión Volaire” y tropas coloniales en apoyo de Franco?', a: ['Italia', 'Portugal', 'Francia'], correct: 0 },
  { q: '¿Qué dictador portugués apoyó la causa de Franco?', a: ['Salazar', 'Marcelo Caetano', 'Sidónio Pais'], correct: 0 },
  { q: '¿Qué dirigente republicano se exilió a México al terminar la guerra?', a: ['Manuel Azaña', 'Juan Negrín', 'Francisco Largo Caballero'], correct: 0 },
  { q: '¿Qué líder sindicalista fue clave en la CNT durante la guerra?', a: ['Federica Montseny', 'Ángel Pestaña', 'Andreu Nin'], correct: 0 },
  { q: '¿Qué rol tuvo la URSS en la guerra?', a: ['Envió armas y asesores al bando republicano', 'Reconoció al gobierno de Franco', 'Se mantuvo neutral'], correct: 0 },
  { q: '¿Qué país creó el Comité de No Intervención junto con Reino Unido?', a: ['Francia', 'Alemania', 'Italia'], correct: 0 },
  { q: '¿Qué importante batalla se libró en el invierno de 1937-1938 en condiciones extremas?', a: ['Batalla de Teruel', 'Batalla del Ebro', 'Batalla del Jarama'], correct: 0 },
  { q: '¿Qué dirigente comunista español tuvo gran influencia en el gobierno de Negrín?', a: ['Dolores Ibárruri', 'Santiago Carrillo', 'Vicente Rojo'], correct: 0 },
  { q: '¿Qué general republicano destacó en la defensa de Madrid?', a: ['Vicente Rojo', 'Miaja', 'Casado'], correct: 0 },
  { q: '¿Qué ocurrió en los “sucesos de mayo” de 1937 en Barcelona?', a: ['Enfrentamientos entre comunistas y anarquistas', 'Bombardeo alemán', 'Entrada de tropas franquistas'], correct: 0 },
  { q: '¿Qué institución religiosa fue duramente perseguida en zona republicana?', a: ['La Iglesia católica', 'La Iglesia ortodoxa', 'Las órdenes protestantes'], correct: 0 },
  { q: '¿Qué territorio español quedó bajo control franquista desde el inicio?', a: ['Navarra', 'Asturias', 'Cataluña'], correct: 0 },
  { q: '¿Qué ideología era dominante en Falange Española?', a: ['Fascismo', 'Comunismo', 'Liberalismo'], correct: 0 },
  { q: '¿Qué ciudad fue bombardeada intensamente además de Guernica?', a: ['Cabra', 'Barcelona', 'Valladolid'], correct: 0 },
  { q: '¿Qué líder socialista fue clave en la política republicana antes de Negrín?', a: ['Francisco Largo Caballero', 'Indalecio Prieto', 'Santiago Carrillo'], correct: 0 },
  { q: '¿Qué batalla de 1936 consolidó a Franco como líder indiscutido de los nacionales?', a: ['Alcázar de Toledo', 'Jarama', 'Ebro'], correct: 0 },
  { q: '¿Qué gran potencia reconoció oficialmente a Franco antes de acabar la guerra?', a: ['Francia', 'Reino Unido', 'Estados Unidos'], correct: 0 },
  { q: '¿Qué consecuencia tuvo la caída de Cataluña en 1939?', a: ['Éxodo republicano hacia Francia', 'Caída inmediata de Madrid', 'Paz negociada con Franco'], correct: 0 },
  { q: '¿Qué grupo combatió en columnas milicianas al inicio de la guerra?', a: ['Anarquistas y socialistas', 'Carlistas y falangistas', 'Monárquicos'], correct: 0 },
  { q: '¿Qué significó la expresión “quinta columna” usada durante el asedio de Madrid?', a: ['Simpatizantes franquistas dentro de la ciudad', 'El quinto ejército de Franco', 'Un grupo de brigadistas'], correct: 0 },
  { q: '¿Qué dirigente nacional fue conocido por sus discursos radiofónicos desde Sevilla?', a: ['Queipo de Llano', 'Mola', 'Varela'], correct: 0 },
  { q: '¿Qué líder político republicano fue ejecutado al inicio de la guerra?', a: ['José Antonio Primo de Rivera', 'Azaña', 'Calvo Sotelo'], correct: 0 }
]);
