addQuestions('easy', [
  { q: '¿En qué año comenzó la Guerra Civil Española?', a: ['1936', '1939', '1923'], correct: 0 },
  { q: '¿En qué año terminó la Guerra Civil Española?', a: ['1939', '1945', '1933'], correct: 0 },
  { q: '¿Qué dos bandos se enfrentaron en la Guerra Civil Española?', a: ['Republicanos y Nacionales', 'Liberales y Conservadores', 'Realistas y Constitucionales'], correct: 0 },
  { q: '¿Quién lideró el bando sublevado que ganó la guerra?', a: ['Francisco Franco', 'José Antonio Primo de Rivera', 'Manuel Azaña'], correct: 0 },
  { q: '¿Qué régimen se instauró tras la Guerra Civil?', a: ['Dictadura franquista', 'Monarquía parlamentaria', 'República federal'], correct: 0 },
  { q: '¿Quién era el presidente de la República al estallar la guerra?', a: ['Manuel Azaña', 'Niceto Alcalá-Zamora', 'Juan Negrín'], correct: 0 },
  { q: '¿Qué país apoyó principalmente a los nacionales con armas y tropas?', a: ['Alemania nazi', 'Francia', 'Unión Soviética'], correct: 0 },
  { q: '¿Qué país apoyó principalmente a los republicanos?', a: ['Unión Soviética', 'Italia fascista', 'Portugal'], correct: 0 },
  { q: '¿Cómo se llamaban las tropas extranjeras voluntarias que lucharon con los republicanos?', a: ['Brigadas Internacionales', 'Legión Extranjera', 'Compañías Internacionales'], correct: 0 },
  { q: '¿Qué ciudad fue duramente bombardeada en 1937 y pintada por Picasso?', a: ['Guernica', 'Bilbao', 'Madrid'], correct: 0 },
  { q: '¿Qué ideología defendía el bando republicano?', a: ['Democracia y reformas sociales', 'Monarquía absoluta', 'Imperio colonial'], correct: 0 },
  { q: '¿Qué ideología defendía el bando nacional?', a: ['Autoritarismo y tradición', 'Anarquismo', 'Liberalismo económico'], correct: 0 },
  { q: '¿Cuál fue el principal objetivo del golpe militar de 1936?', a: ['Derrocar a la República', 'Restaurar la monarquía borbónica', 'Anexar Portugal'], correct: 0 },
  { q: '¿Qué general fue clave en el inicio del golpe militar?', a: ['Emilio Mola', 'Francisco Largo Caballero', 'Indalecio Prieto'], correct: 0 },
  { q: '¿Qué dictador italiano envió tropas y aviones para apoyar a Franco?', a: ['Benito Mussolini', 'Adolf Hitler', 'Salazar'], correct: 0 },
  { q: '¿Qué ciudad fue la capital de la República durante la guerra?', a: ['Valencia', 'Barcelona', 'Madrid'], correct: 0 },
  { q: '¿Qué lema usaba el bando nacional en la guerra?', a: ['¡Arriba España!', '¡No pasarán!', '¡Viva la República!'], correct: 0 },
  { q: '¿Qué lema usaba el bando republicano durante la defensa de Madrid?', a: ['¡No pasarán!', '¡Arriba España!', '¡Viva el Rey!'], correct: 0 },
  { q: '¿Qué importante batalla en 1937 fue un intento de tomar Madrid?', a: ['Batalla del Jarama', 'Batalla de Brunete', 'Batalla de Teruel'], correct: 0 },
  { q: '¿Qué importante batalla de 1938 marcó un punto decisivo?', a: ['Batalla del Ebro', 'Batalla de Bailén', 'Batalla de Guadalajara'], correct: 0 },
  { q: '¿Qué tipo de gobierno era la Segunda República Española?', a: ['Democracia parlamentaria', 'Dictadura', 'Monarquía absoluta'], correct: 0 },
  { q: '¿Qué ciudad cayó en 1939 marcando el final de la guerra?', a: ['Madrid', 'Barcelona', 'Sevilla'], correct: 0 },
  { q: '¿Qué partido fundó José Antonio Primo de Rivera?', a: ['Falange Española', 'Partido Comunista', 'PSOE'], correct: 0 },
  { q: '¿Qué grupo político tuvo gran peso en el bando republicano?', a: ['Socialistas y comunistas', 'Falangistas', 'Monárquicos'], correct: 0 },
  { q: '¿Qué grupo político tuvo gran peso en el bando nacional?', a: ['Falangistas y carlistas', 'Anarquistas', 'Republicanos moderados'], correct: 0 },
  { q: '¿Qué famoso escritor británico participó en la guerra?', a: ['George Orwell', 'J. R. R. Tolkien', 'Aldous Huxley'], correct: 0 },
  { q: '¿Qué nombre recibían los soldados marroquíes que lucharon con Franco?', a: ['Regulares', 'Maulets', 'Guanches'], correct: 0 },
  { q: '¿Qué acontecimiento internacional coincidió con la Guerra Civil?', a: ['Ascenso del fascismo en Europa', 'La Primera Guerra Mundial', 'La Guerra de Corea'], correct: 0 },
  { q: '¿Qué gran potencia democrática decidió no intervenir oficialmente?', a: ['Francia y Reino Unido', 'Alemania e Italia', 'Portugal'], correct: 0 },
  { q: '¿Qué organización internacional intentó mantener la no intervención?', a: ['Comité de No Intervención', 'Naciones Unidas', 'Liga Árabe'], correct: 0 },
  { q: '¿Qué tipo de armas probaron los alemanes en Guernica?', a: ['Bombardeos aéreos', 'Tanques pesados', 'Gas venenoso'], correct: 0 },
  { q: '¿Qué ciudad fue sede de un gobierno republicano en el exilio?', a: ['París', 'Lisboa', 'Roma'], correct: 0 },
  { q: '¿Qué política aplicó Franco tras ganar la guerra?', a: ['Represión y exilio de opositores', 'Reformas democráticas', 'Abolición del ejército'], correct: 0 },
  { q: '¿Qué grupo religioso apoyó mayoritariamente al bando nacional?', a: ['La Iglesia católica', 'Los protestantes', 'Los ortodoxos'], correct: 0 },
  { q: '¿Qué dictador alemán intervino en la guerra apoyando a Franco?', a: ['Adolf Hitler', 'Kaiser Guillermo II', 'Otto von Bismarck'], correct: 0 },
  { q: '¿Qué batalla fue la más larga y sangrienta de la guerra?', a: ['Batalla del Ebro', 'Batalla de Brunete', 'Batalla del Jarama'], correct: 0 },
  { q: '¿Qué ideología compartían Hitler, Mussolini y Franco?', a: ['Fascismo y autoritarismo', 'Comunismo', 'Liberalismo'], correct: 0 },
  { q: '¿Qué ocurrió con la monarquía española tras la guerra?', a: ['Se mantuvo en el exilio hasta 1975', 'Fue restaurada de inmediato', 'Continuó reinando Alfonso XIII'], correct: 0 },
  { q: '¿Qué nombre recibió el periodo de guerra contra la República?', a: ['Alzamiento nacional', 'Revolución de Octubre', 'Semana Trágica'], correct: 0 },
  { q: '¿Qué color se asocia con el bando republicano?', a: ['Rojo', 'Negro', 'Azul'], correct: 0 }
]);
