addQuestions('hard', [
  { q: '¿Qué líder monárquico fue asesinado en julio de 1936, precipitando el estallido de la guerra?', a: ['José Calvo Sotelo', 'José Antonio Primo de Rivera', 'Gil Robles'], correct: 0 },
  { q: '¿Qué general nacional murió en accidente aéreo al inicio del levantamiento?', a: ['José Sanjurjo', 'Emilio Mola', 'Manuel Goded'], correct: 0 },
  { q: '¿Qué pacto secreto firmaron Alemania e Italia para coordinar su ayuda a Franco?', a: ['Pacto de la Amistad Germano-Italiana', 'Pacto Antikomintern', 'Tratado de Roma'], correct: 0 },
  { q: '¿Qué operación permitió trasladar al ejército de África a la península en 1936?', a: ['El puente aéreo del Estrecho', 'La operación Mar Cantábrico', 'El desembarco de Alhucemas'], correct: 0 },
  { q: '¿Qué general sublevado fue apodado “El Caudillo de Galicia”?', a: ['Emilio Mola', 'Franco', 'Queipo de Llano'], correct: 0 },
  { q: '¿Qué dirigente republicano formó el Consejo de Defensa de Madrid en 1936?', a: ['José Miaja', 'Vicente Rojo', 'Casado'], correct: 0 },
  { q: '¿Qué organización de inteligencia soviética operó en España durante la guerra?', a: ['NKVD', 'KGB', 'GRU'], correct: 0 },
  { q: '¿Qué operación militar nacional dividió en dos el territorio republicano en 1937?', a: ['La campaña del Norte', 'La ofensiva de Aragón', 'La operación de Córdoba'], correct: 0 },
  { q: '¿Qué general republicano dirigió la ofensiva del Ebro?', a: ['Vicente Rojo', 'Miaja', 'Hernández Saravia'], correct: 0 },
  { q: '¿Qué dirigente comunista fue asesinado por agentes soviéticos en 1937?', a: ['Andreu Nin', 'Buenaventura Durruti', 'Ángel Pestaña'], correct: 0 },
  { q: '¿Qué consecuencia internacional tuvo el bombardeo de Guernica?', a: ['Condena mundial del nazismo', 'Entrada de EE.UU. en la guerra', 'Alianza franco-británica con Franco'], correct: 0 },
  { q: '¿Qué nombre recibió la última ofensiva republicana en 1939?', a: ['Golpe de Casado', 'Ofensiva de Extremadura', 'Operación Madrid'], correct: 0 },
  { q: '¿Qué dirigente militar republicano encabezó el golpe contra Negrín en marzo de 1939?', a: ['Segismundo Casado', 'Vicente Rojo', 'José Miaja'], correct: 0 },
  { q: '¿Qué misión cumplió la “Socorro Rojo Internacional”?', a: ['Apoyar a presos y familias republicanas', 'Recaudar fondos para Franco', 'Coordinar la ayuda de Mussolini'], correct: 0 },
  { q: '¿Qué periódico era órgano de propaganda de Falange?', a: ['Arriba', 'El Socialista', 'Mundo Obrero'], correct: 0 },
  { q: '¿Qué ciudad fue sede del Gobierno vasco autónomo durante la guerra?', a: ['Bilbao', 'San Sebastián', 'Vitoria'], correct: 0 },
  { q: '¿Qué presidente de la Generalitat de Cataluña dirigió la región durante la guerra?', a: ['Lluís Companys', 'Francesc Macià', 'Josep Tarradellas'], correct: 0 },
  { q: '¿Qué líder republicano defendió el “Plan de los Trece Puntos”?', a: ['Juan Negrín', 'Azaña', 'Largo Caballero'], correct: 0 },
  { q: '¿Qué batalla en 1937 aseguró a los nacionales el control del norte industrial?', a: ['Batalla de Santander', 'Batalla de Brunete', 'Batalla de Jarama'], correct: 0 },
  { q: '¿Qué político republicano murió en el exilio en Montauban en 1940?', a: ['Manuel Azaña', 'Indalecio Prieto', 'Juan Negrín'], correct: 0 },
  { q: '¿Qué país acogió a un gran número de refugiados vascos durante la guerra?', a: ['Reino Unido', 'Portugal', 'Estados Unidos'], correct: 0 },
  { q: '¿Qué general nacional fue conocido por la “columna de la muerte” en Badajoz?', a: ['Yagüe', 'Queipo de Llano', 'Varela'], correct: 0 },
  { q: '¿Qué dirigente falangista fue ejecutado en Alicante en 1936?', a: ['José Antonio Primo de Rivera', 'Ramiro Ledesma Ramos', 'Onésimo Redondo'], correct: 0 },
  { q: '¿Qué dirigente comunista español se exilió en Moscú y tuvo gran influencia en el PCE?', a: ['Dolores Ibárruri', 'Santiago Carrillo', 'Vicente Uribe'], correct: 0 },
  { q: '¿Qué nombre recibió el sistema de campos de concentración franquistas tras la guerra?', a: ['Batallones de Trabajadores', 'Brigadas Internacionales', 'Milicias Nacionales'], correct: 0 },
  { q: '¿Qué base naval fue crucial para los nacionales en el Mediterráneo?', a: ['Base de Mallorca', 'Base de Cartagena', 'Base de Cádiz'], correct: 0 },
  { q: '¿Qué ciudad catalana sufrió un bombardeo devastador en 1938?', a: ['Barcelona', 'Girona', 'Tarragona'], correct: 0 },
  { q: '¿Qué líder del POUM fue acusado de trotskista y ejecutado?', a: ['Andreu Nin', 'Joaquín Maurín', 'Francisco Ascaso'], correct: 0 },
  { q: '¿Qué documento firmó Franco en Burgos en 1936 consolidando su poder?', a: ['Decreto de Unificación', 'Ley de Responsabilidades Políticas', 'Fuero del Trabajo'], correct: 0 },
  { q: '¿Qué internacionalista chileno se destacó como piloto en la defensa de Madrid?', a: ['Ramón Mercader', 'Carlos Contreras', 'Manuel Rojas'], correct: 0 },
  { q: '¿Qué famosa fotógrafa inmortalizó la guerra con sus imágenes?', a: ['Gerda Taro', 'Dorothea Lange', 'Annie Leibovitz'], correct: 0 },
  { q: '¿Qué líder de la Iglesia legitimó a Franco con la carta colectiva del episcopado?', a: ['Cardenal Gomá', 'Cardenal Segura', 'Cardenal Vidal i Barraquer'], correct: 0 },
  { q: '¿Qué político vasco fue lehendakari durante la guerra?', a: ['José Antonio Aguirre', 'Ramón Rubial', 'Iñaki de Arzalluz'], correct: 0 },
  { q: '¿Qué famoso brigadista canadiense escribió sobre su experiencia en España?', a: ['Charles Donnelly', 'Alvah Bessie', 'Mackenzie-Papineau'], correct: 0 },
  { q: '¿Qué significó la “Causa General” abierta tras la guerra?', a: ['Investigación franquista de crímenes republicanos', 'Un plan económico', 'Un proceso de reconciliación'], correct: 0 },
  { q: '¿Qué dirigente socialista propuso un pacto con los nacionalistas en 1937?', a: ['Indalecio Prieto', 'Largo Caballero', 'Besteiro'], correct: 0 },
  { q: '¿Qué nombre recibió el gobierno de Franco instalado en Burgos?', a: ['Junta de Defensa Nacional', 'Consejo de Burgos', 'Gobierno Provisional'], correct: 0 },
  { q: '¿Qué unidad militar nacional fue célebre por su dureza en combate?', a: ['La Legión', 'Los Federales', 'Los Voluntarios de Navarra'], correct: 0 },
  { q: '¿Qué dirigente republicano fue acusado de rendir Madrid en 1939?', a: ['Segismundo Casado', 'Vicente Rojo', 'Miaja'], correct: 0 },
  { q: '¿Qué acuerdo internacional de 1936 intentó frenar la intervención extranjera en España?', a: ['Pacto de No Intervención', 'Acuerdo de Londres', 'Conferencia de Ginebra'], correct: 0 }
]);
