addQuestions('easy', [
  { q: '¿Qué característica principal tienen las plantas crasas y suculentas?', a: ['Almacenan agua en sus hojas o tallos', 'Siempre crecen en el mar', 'No necesitan sol'], correct: 0 },
  { q: '¿Dónde suelen crecer las plantas crasas de manera natural?', a: ['En lugares secos y soleados', 'En bosques húmedos', 'En la nieve'], correct: 0 },
  { q: '¿Cómo son normalmente las hojas de las suculentas?', a: ['Gruesas y carnosas', 'Muy finas y largas', 'Con espinas duras'], correct: 0 },
  { q: '¿Qué necesitan las suculentas para crecer bien?', a: ['Mucha luz', 'Mucha sombra', 'Frío constante'], correct: 0 },
  { q: '¿Qué pasa si riegas demasiado una planta suculenta?', a: ['Se pudren sus raíces', 'Crece más rápido', 'Saca flores'], correct: 0 },
  { q: '¿Qué parte del día prefieren para recibir sol la mayoría de suculentas?', a: ['La mañana', 'La medianoche', 'La tarde-noche'], correct: 0 },
  { q: '¿Cómo suelen ser las flores de las plantas suculentas?', a: ['Muy vistosas y de colores vivos', 'Pequeñas y siempre blancas', 'Nunca florecen'], correct: 0 },
  { q: '¿Qué material es mejor para las macetas de suculentas?', a: ['Barro o terracota', 'Plástico cerrado', 'Vidrio sin agujeros'], correct: 0 },
  { q: '¿Qué tipo de tierra necesitan las suculentas?', a: ['Tierra que drene rápido', 'Tierra muy compacta', 'Solo arena de playa'], correct: 0 },
  { q: '¿Cómo se reproducen fácilmente muchas suculentas?', a: ['A partir de hojas o esquejes', 'Solo con semillas', 'En agua como los nenúfares'], correct: 0 },
  { q: '¿Qué planta crasa es famosa por sus pinchos?', a: ['El cactus', 'El aloe', 'La echeveria'], correct: 0 },
  { q: '¿Qué planta suculenta se usa mucho para curar quemaduras en la piel?', a: ['El aloe vera', 'El cactus de Navidad', 'La siempreviva'], correct: 0 },
  { q: '¿Qué pasa con las hojas de muchas suculentas si no reciben luz suficiente?', a: ['Se estiran y pierden forma', 'Se vuelven negras', 'Se llenan de agua'], correct: 0 },
  { q: '¿Qué forma suelen tener las hojas de las echeverias?', a: ['En forma de roseta', 'Como agujas largas', 'Enredadas como lianas'], correct: 0 },
  { q: '¿Qué parte del cactus almacena más agua?', a: ['El tallo', 'Las espinas', 'Las flores'], correct: 0 },
  { q: '¿Por qué las suculentas soportan bien la sequía?', a: ['Porque guardan agua en sus tejidos', 'Porque no tienen raíces', 'Porque viven solo de aire'], correct: 0 },
  { q: '¿Qué suculenta suele colgar en forma de bolitas verdes?', a: ['El rosario de perlas', 'El cactus barril', 'El aloe'], correct: 0 },
  { q: '¿Qué suculenta se conoce por sus hojas en forma de corazón?', a: ['La planta corazón', 'El cactus orejas', 'La planta lápiz'], correct: 0 },
  { q: '¿Qué debes evitar al cuidar suculentas?', a: ['Regar demasiado', 'Dejarlas al sol', 'Usar macetas de barro'], correct: 0 },
  { q: '¿Qué indica que una suculenta está feliz y sana?', a: ['Colores vivos y hojas firmes', 'Hojas blandas y caídas', 'Tierra siempre encharcada'], correct: 0 },
  { q: '¿Qué colores pueden tener las suculentas además del verde?', a: ['Rojos, morados y amarillos', 'Solo azul', 'Siempre verde oscuro'], correct: 0 },
  { q: '¿Qué pasa si a una suculenta le falta agua mucho tiempo?', a: ['Sus hojas se arrugan', 'Se pone más verde', 'Se llena de flores'], correct: 0 },
  { q: '¿Qué función cumplen las espinas de un cactus?', a: ['Proteger y reducir pérdida de agua', 'Hacer más bonitas las flores', 'Atrapar insectos'], correct: 0 },
  { q: '¿Cómo suelen crecer las raíces de las suculentas?', a: ['Poco profundas', 'Muy largas como un pino', 'Flotando en el aire'], correct: 0 },
  { q: '¿Qué suculenta suele florecer en invierno en forma de estrella roja?', a: ['El cactus de Navidad', 'El aloe', 'La siempreviva'], correct: 0 },
  { q: '¿Qué suculenta se parece a piedras pequeñas?', a: ['Las piedras vivas', 'El aloe', 'El cactus orejas'], correct: 0 },
  { q: '¿Qué hacen muchas suculentas cuando tienen demasiado sol?', a: ['Cambian de color', 'Se vuelven transparentes', 'Sacan raíces aéreas'], correct: 0 },
  { q: '¿Qué parte del día es mejor para regar una suculenta?', a: ['Por la mañana', 'Al mediodía', 'De noche'], correct: 0 },
  { q: '¿Qué se recomienda hacer después de cortar una hoja para reproducirla?', a: ['Dejarla secar unos días', 'Plantarla de inmediato', 'Meterla en agua'], correct: 0 },
  { q: '¿Qué pasa si una suculenta está en un sitio muy oscuro?', a: ['Se debilita y pierde color', 'Florece más', 'Se llena de espinas'], correct: 0 },
  { q: '¿Qué suculenta tiene hojas largas con bordes dentados y gel en su interior?', a: ['El aloe vera', 'El cactus bola', 'El rosario de perlas'], correct: 0 },
  { q: '¿Qué tipo de clima imitan los terrarios con suculentas?', a: ['Desértico y seco', 'Tropical y lluvioso', 'Polar'], correct: 0 },
  { q: '¿Qué suculenta es típica como regalo por su forma de flor de rosa?', a: ['La echeveria', 'El cactus orejas', 'La planta corazón'], correct: 0 },
  { q: '¿Qué ocurre si a un cactus se le quitan todas las espinas?', a: ['Puede sobrevivir pero más desprotegido', 'Se muere al instante', 'Se convierte en aloe'], correct: 0 },
  { q: '¿Qué suculenta cuelga en forma de largas trenzas verdes?', a: ['Cola de burro', 'Rosario de perlas', 'Orejas de conejo'], correct: 0 },
  { q: '¿Qué debes comprobar siempre en una maceta de suculentas?', a: ['Que tenga agujero de drenaje', 'Que pese mucho', 'Que sea muy grande'], correct: 0 },
  { q: '¿Qué época del año florecen más las suculentas?', a: ['Primavera y verano', 'Invierno', 'Otoño'], correct: 0 },
  { q: '¿Qué pasa si trasplantas una suculenta y la riegas enseguida?', a: ['Puede pudrirse', 'Crecen más raíces', 'Florece antes'], correct: 0 },
  { q: '¿Qué uso tienen las suculentas además de decorar?', a: ['Algunas son medicinales', 'Sirven de leña', 'Dan sombra en verano'], correct: 0 },
  { q: '¿Qué debes hacer con las hojas secas de la base de una suculenta?', a: ['Quitarlas con cuidado', 'Regarlas más', 'Pintarlas'], correct: 0 }
]);
