addQuestions('intermediate', [
  { q: '¿Por qué las suculentas tienen hojas tan gruesas?', a: ['Para guardar agua', 'Para atraer insectos', 'Para hacer sombra'], correct: 0 },
  { q: '¿Qué función cumplen las ceras en la superficie de muchas suculentas?', a: ['Reducir la pérdida de agua', 'Hacerlas más suaves', 'Cambiar su color'], correct: 0 },
  { q: '¿Qué suculenta se suele usar en cosmética por su gel interior?', a: ['El aloe vera', 'El cactus bola', 'La cola de burro'], correct: 0 },
  { q: '¿Qué sucede si riegas una suculenta con agua acumulada en el plato de la maceta?', a: ['Las raíces se pudren', 'La planta crece más rápido', 'Las hojas se vuelven más brillantes'], correct: 0 },
  { q: '¿Qué suculenta es conocida por parecerse a piedras para camuflarse?', a: ['Las piedras vivas', 'El cactus erizo', 'La echeveria'], correct: 0 },
  { q: '¿Qué significa que una suculenta se “etiola”?', a: ['Se estira buscando luz', 'Se llena de flores', 'Se seca por exceso de sol'], correct: 0 },
  { q: '¿Qué ocurre si se arrancan espinas de un cactus?', a: ['La planta queda más vulnerable', 'La planta se seca', 'La planta muere al instante'], correct: 0 },
  { q: '¿Qué suculenta cuelga formando cadenas de bolitas verdes?', a: ['Rosario de perlas', 'Cola de burro', 'Orejas de conejo'], correct: 0 },
  { q: '¿Por qué el barro o terracota es mejor que el plástico para macetas de suculentas?', a: ['Porque transpira y seca antes la tierra', 'Porque pesa menos', 'Porque es más colorido'], correct: 0 },
  { q: '¿Qué suculenta tiene hojas en forma de corazón y se regala en San Valentín?', a: ['La planta corazón', 'La echeveria', 'La planta lápiz'], correct: 0 },
  { q: '¿Qué ocurre cuando una suculenta cambia de color al recibir más sol?', a: ['Se estresa y activa defensas', 'Se está secando', 'Está enferma'], correct: 0 },
  { q: '¿Qué nombre popular recibe la suculenta con hojas largas colgantes llamadas “cola de burro”?', a: ['Cola de burro', 'Trenza de ángel', 'Cabellera verde'], correct: 0 },
  { q: '¿Qué diferencia hay entre un cactus y otras suculentas?', a: ['Los cactus tienen espinas verdaderas', 'Los cactus siempre son grandes', 'Las demás no almacenan agua'], correct: 0 },
  { q: '¿Qué pasa si una suculenta florece y muere después?', a: ['Era una planta de vida corta', 'Se regó mal', 'Le faltó sol'], correct: 0 },
  { q: '¿Qué tipo de riego se recomienda para las suculentas?', a: ['Riegos espaciados y abundantes', 'Riegos diarios', 'Riego constante por goteo'], correct: 0 },
  { q: '¿Qué parte de las suculentas puede producir nuevas plantas fácilmente?', a: ['Hojas o tallos', 'Flores secas', 'Espinas'], correct: 0 },
  { q: '¿Qué suculenta florece en invierno y se llama cactus de Navidad?', a: ['El cactus de Navidad', 'El cactus barril', 'El rosario de perlas'], correct: 0 },
  { q: '¿Qué indica que una suculenta tiene hojas blandas y arrugadas?', a: ['Falta de agua', 'Exceso de sol', 'Falta de abono'], correct: 0 },
  { q: '¿Qué indican manchas negras en hojas de suculentas?', a: ['Podredumbre por exceso de agua', 'Falta de sol', 'Enfermedad por insectos siempre'], correct: 0 },
  { q: '¿Qué condición hace que muchas suculentas cambien a tonos rojizos o morados?', a: ['Mucho sol', 'Exceso de agua', 'Poca tierra'], correct: 0 },
  { q: '¿Qué ocurre si plantas suculentas en tierra muy compacta?', a: ['Las raíces no respiran y mueren', 'Crecen más rápido', 'Sacan más flores'], correct: 0 },
  { q: '¿Qué se recomienda hacer antes de regar suculentas?', a: ['Comprobar que la tierra está seca', 'Echarles fertilizante', 'Mover la maceta'], correct: 0 },
  { q: '¿Qué suculenta tiene hojas que parecen pequeñas rosas?', a: ['Echeveria', 'Rosario de perlas', 'Cola de burro'], correct: 0 },
  { q: '¿Qué pasa si cortas una hoja de suculenta y la plantas enseguida?', a: ['Se puede pudrir', 'Siempre florece', 'Saca raíces más rápido'], correct: 0 },
  { q: '¿Qué suculenta se cuelga en balcones y se conoce como “orejas de conejo”?', a: ['Orejas de conejo', 'Cola de burro', 'Rosario de perlas'], correct: 0 },
  { q: '¿Qué indica que una suculenta tiene hojas transparentes o vidriosas?', a: ['Está al límite de agua', 'Tiene exceso de sol', 'Está lista para florecer'], correct: 0 },
  { q: '¿Qué debes evitar cuando trasplantas una suculenta?', a: ['Regarla enseguida', 'Usar maceta más grande', 'Cambiarle la tierra'], correct: 0 },
  { q: '¿Qué suculenta se usa como planta colgante con forma de lágrimas verdes?', a: ['Rosario de lágrimas', 'Cola de burro', 'Echeveria'], correct: 0 },
  { q: '¿Qué hace el sol de la mañana en las suculentas?', a: ['Favorece su color y forma', 'Las quema', 'Las marchita'], correct: 0 },
  { q: '¿Qué pasa si dejas una suculenta en agua varios días?', a: ['Se pudren sus raíces', 'Crecen más rápido', 'Se llena de flores'], correct: 0 },
  { q: '¿Qué herramienta es útil para regar suculentas sin mojar demasiado las hojas?', a: ['Un pulverizador o regadera fina', 'Una manguera a presión', 'Un cubo de agua'], correct: 0 },
  { q: '¿Qué suculenta tiene tallos finos en forma de lápices verdes?', a: ['Planta lápiz', 'Rosario de perlas', 'Echeveria'], correct: 0 },
  { q: '¿Qué indica que las raíces de una suculenta salen por debajo de la maceta?', a: ['Necesita trasplante', 'Necesita más sol', 'Está enferma'], correct: 0 },
  { q: '¿Qué pasa con muchas suculentas cuando florecen?', a: ['Algunas mueren después', 'Se vuelven más verdes', 'Dejan de guardar agua'], correct: 0 },
  { q: '¿Qué tipo de fertilizante se recomienda para suculentas?', a: ['Bajo en nitrógeno', 'Muy rico en nitrógeno', 'Solo estiércol'], correct: 0 },
  { q: '¿Qué pasa si una suculenta recibe sol directo fuerte sin acostumbrarse?', a: ['Se quema y salen manchas', 'Crece más rápido', 'Florece enseguida'], correct: 0 },
  { q: '¿Qué debes hacer si una hoja de suculenta se arruga pero la planta sigue verde?', a: ['Es normal, quitarla', 'Regar urgentemente', 'Cambiarla de maceta'], correct: 0 },
  { q: '¿Qué suculenta es famosa por colgar en cascadas largas y verdes?', a: ['Cola de burro', 'Planta lápiz', 'Orejas de conejo'], correct: 0 },
  { q: '¿Qué clima imitan muchas colecciones de suculentas en casa?', a: ['Desierto soleado', 'Selva húmeda', 'Zona polar'], correct: 0 }
]);
