addQuestions('hard', [
  { q: '¿Por qué muchas suculentas desarrollan colores rojos o morados intensos?', a: ['Por estrés de sol o frío', 'Por exceso de agua', 'Por falta de tierra'], correct: 0 },
  { q: '¿Qué sucede si una suculenta florece y luego muere?', a: ['Era una planta de ciclo único', 'La tierra estaba en mal estado', 'Faltaba fertilizante'], correct: 0 },
  { q: '¿Qué mecanismo permite a los cactus abrir sus estomas de noche y no de día?', a: ['Ahorrar agua en climas secos', 'Atraer insectos nocturnos', 'Dormir como los animales'], correct: 0 },
  { q: '¿Qué indica que una suculenta tiene tallos blandos y acuosos?', a: ['Podredumbre interna', 'Floración próxima', 'Exceso de fertilizante'], correct: 0 },
  { q: '¿Qué diferencia tienen los cactus frente a otras suculentas?', a: ['Tienen areolas de donde salen espinas y flores', 'No almacenan agua', 'No necesitan luz solar'], correct: 0 },
  { q: '¿Por qué muchas suculentas cambian de color en invierno?', a: ['Por frío y menos horas de luz', 'Porque florecen todas', 'Porque reciben más agua'], correct: 0 },
  { q: '¿Qué significa que una suculenta tenga raíces aéreas en sus tallos?', a: ['Busca más agua o estabilidad', 'Está enferma', 'Va a florecer'], correct: 0 },
  { q: '¿Qué ocurre si un cactus crece muy alargado y delgado?', a: ['Tiene poca luz', 'Tiene demasiada agua', 'Va a florecer'], correct: 0 },
  { q: '¿Qué es un “hijuelo” en una suculenta?', a: ['Una nueva planta que brota junto a la madre', 'Una hoja seca', 'Una flor cortada'], correct: 0 },
  { q: '¿Qué suele pasar a las suculentas cuando están en sombra constante?', a: ['Se etiolan y se deforman', 'Florecen más', 'Sacan más espinas'], correct: 0 },
  { q: '¿Qué se recomienda hacer con una suculenta quemada por el sol?', a: ['Moverla a sombra progresiva', 'Regarla en exceso', 'Quitarle todas las hojas'], correct: 0 },
  { q: '¿Qué tipo de agua puede dañar más a las suculentas a largo plazo?', a: ['Agua con mucha cal', 'Agua de lluvia', 'Agua destilada'], correct: 0 },
  { q: '¿Qué significa que una suculenta “entra en reposo”?', a: ['Que deja de crecer en ciertas estaciones', 'Que muere después de florecer', 'Que pierde todas sus hojas'], correct: 0 },
  { q: '¿Qué provoca que un cactus saque flores solo de un lado?', a: ['La orientación constante al sol', 'Falta de nutrientes', 'Exceso de agua'], correct: 0 },
  { q: '¿Qué indica que una suculenta tenga hojas arrugadas pero la tierra sigue húmeda?', a: ['Raíces dañadas o podridas', 'Falta de luz', 'Exceso de fertilizante'], correct: 0 },
  { q: '¿Qué se recomienda hacer después de cortar un tallo para reproducirlo?', a: ['Dejarlo cicatrizar antes de plantar', 'Plantarlo enseguida', 'Meterlo en agua'], correct: 0 },
  { q: '¿Qué tipo de fertilizante puede dañar a las suculentas?', a: ['Uno muy rico en nitrógeno', 'Uno bajo en fósforo', 'Uno diluido en agua'], correct: 0 },
  { q: '¿Por qué algunas suculentas parecen cubrirse de una capa blanca o polvosa?', a: ['Es protección natural contra el sol', 'Es señal de enfermedad', 'Es exceso de riego'], correct: 0 },
  { q: '¿Qué pasa si cortas una flor de suculenta demasiado pronto?', a: ['La planta pierde energía innecesariamente', 'La planta muere siempre', 'Las hojas cambian de color'], correct: 0 },
  { q: '¿Qué indica que un cactus está amarilleando desde la base?', a: ['Problemas de raíces o exceso de agua', 'Floración próxima', 'Falta de espinas'], correct: 0 },
  { q: '¿Qué método usan algunas suculentas para sobrevivir en lugares rocosos?', a: ['Camuflarse como piedras', 'Sacar raíces muy profundas', 'Vivir solo del aire'], correct: 0 },
  { q: '¿Qué sucede si una suculenta crece torcida hacia un lado?', a: ['Busca más luz', 'Está a punto de florecer', 'Le sobra agua'], correct: 0 },
  { q: '¿Qué significa que una suculenta tenga “crestas” en vez de forma normal?', a: ['Es una mutación de crecimiento', 'Está enferma', 'Recibe demasiada agua'], correct: 0 },
  { q: '¿Qué parte de la suculenta conviene no mojar al regar?', a: ['Las hojas', 'Las raíces', 'La maceta'], correct: 0 },
  { q: '¿Qué pasa si una suculenta se congela en invierno?', a: ['El agua de sus tejidos la rompe por dentro', 'Saca más flores en primavera', 'Crece más rápido'], correct: 0 },
  { q: '¿Por qué los cactus de interior suelen crecer más débiles que en exterior?', a: ['Por falta de sol directo', 'Por exceso de agua', 'Por exceso de nutrientes'], correct: 0 },
  { q: '¿Qué hacer si una hoja de suculenta se pudre?', a: ['Quitarla para que no contagie al resto', 'Regar más', 'Dejarla hasta que caiga'], correct: 0 },
  { q: '¿Qué significa que una suculenta florezca en invierno?', a: ['Que tiene un ciclo distinto de crecimiento', 'Que está enferma', 'Que ya no necesita luz'], correct: 0 },
  { q: '¿Qué indica que una suculenta pierde firmeza pero la tierra está seca?', a: ['Necesita agua urgente', 'Está enferma', 'Tiene exceso de luz'], correct: 0 },
  { q: '¿Qué pasa si plantas varias suculentas en la misma maceta muy juntas?', a: ['Compiten por el agua y la luz', 'Todas florecen más', 'Se vuelven más resistentes'], correct: 0 },
  { q: '¿Qué ocurre si una suculenta recibe demasiada sombra durante meses?', a: ['Se deforma y pierde color', 'Saca flores más grandes', 'Aumenta su resistencia'], correct: 0 },
  { q: '¿Qué pasa con una suculenta si sus raíces están muy apretadas en la maceta?', a: ['Se frena su crecimiento', 'Se llena de flores', 'Produce más agua'], correct: 0 },
  { q: '¿Por qué algunas suculentas se parten o agrietan?', a: ['Por exceso de agua acumulada', 'Por frío extremo', 'Por exceso de fertilizante'], correct: 0 },
  { q: '¿Qué hacer si una suculenta tiene cochinillas o pulgones?', a: ['Tratarla con jabón o alcohol', 'Regarla más', 'Cortar todas las hojas'], correct: 0 },
  { q: '¿Qué indica que una suculenta tiene la base marrón y seca?', a: ['Envejecimiento normal', 'Podredumbre mortal', 'Falta de sol'], correct: 0 },
  { q: '¿Qué sucede si se rompe un cactus y se planta la parte cortada?', a: ['Puede enraizar y formar otra planta', 'Se seca siempre', 'Nunca vuelve a crecer'], correct: 0 },
  { q: '¿Por qué algunas suculentas se hacen muy grandes en exterior pero no en interior?', a: ['Porque reciben más sol y espacio', 'Porque se riegan menos', 'Porque el aire es más húmedo'], correct: 0 },
  { q: '¿Qué hacer si una suculenta comienza a pudrirse por exceso de riego?', a: ['Cortar la parte sana y replantar', 'Regar más', 'Dejarla secar sola'], correct: 0 },
  { q: '¿Qué suculentas se usan en medicina popular para curar heridas?', a: ['El aloe y la siempreviva', 'El cactus erizo', 'La cola de burro'], correct: 0 }
]);
